[package]
name = "podseq-core"
description = "Core types and interfaces for podseq"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true

[dependencies]
serde = { workspace = true }
commonware-runtime = { workspace = true }
sui-crypto.workspace = true
base64.workspace = true
